baseURL = 'https://caroljeangallagher.github.io/website/'
languageCode = 'en-us'
title = 'Gallaghers'
theme = 'hugo-theme-cleanwhite'
canonifyURLs = true

[outputs]
home = ["HTML", "RSS"]

[params]
header_image = "images/header-globe.jpg"
SEOTitle = "The Wycliffe Ministry of Steve & Carol Jean Gallagher"
keyword = "Wycliffe, blog, ministry"
sidebar_about_description = "Serving with Wycliffe since 1992"
sidebar_avatar = "images/avatar.jpg"

featured_tags = true 
featured_condition_size = 1 

friends = false
bookmarks = false
about_me = true

[[params.addtional_menus]]
title =  "ARCHIVE"
href =  "/archive/"
[[params.addtional_menus]]
title =  "ABOUT"
href =  "/about/"